# Generated by Django 4.2.17 on 2025-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='address',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
